### PR TITLE
Added ability to skip rows containing sheet metadata

### PR DESCRIPTION
**Pull request by KleinBen**
#33 I implemented the ability for the user to be able to skip header rows.

### CODE REVIEW

**Comment by xverges** [comment]
This is something I needed. In fact, I made the changes myself and later noticed that this PR was available... 

@KleinBen there is a typo in your tests that are making them fail

**Comment by rodrigograca31** [comment]
@xverges thanks for letting me know.
@xverges can u be more specific about the typo? (I have 0 experience with tests)
but his PR has private data....
I don't think I should accept it...

**Comment by xverges** [comment]
@rodrigograca31 I don't think it is private data, but rather sample data files to run the tests. But maybe @KleinBen can confirm that these are not real names
image

Regarding the test failure, @KleinBen should update his PR with a fixed test case, but you can see the failure by clicking on the `Details` field pointing in the travis report https://travis-ci.org/DataGarage/node-xls-json/builds/483178804#L458

**Comment by rodrigograca31** [comment]
Ok, just saw the sheet name is called `MOCK_DATA`....
I will accept the PR and fix the typo.

YAY! :confetti_ball: :tada: :confetti_ball:

**Comment by rodrigograca31** [comment]
Version bumped and published to npm

Thanks for contributing to open source! :heart:

**Pull request merged**
