### PR TITLE
updated dependencies and dev dependencies

### PR DESCRIPTION
**Pull request by NGrant92**
I'm a fan of your xls-to-json package, but your dependencies were very outdated. I thought I'd take the time to update them for you.

### package.json 
- xlsx 0.8.0 --> 0.12.8  
- csv 0.3.6 --> 0.3.7  
- should 3.1.2 --> 13.2.1  
- mocha 1.17.1 --> 5.0.5   

### travs.yml
- node_js: 0.10 --> 8.11.1

I ran an `npm test` after updating the dependencies and I achieved 4/4 passed tests

image

### CODE REVIEW

**Comment by NGrant92** [comment]
Seems Travis CI doesn't like the use of `const` in strict mode? I'll look into this, if you came across this issue, advice would be appreciated.

image

**Comment by NGrant92** [comment]
I found and solved the issue. It was due the me updating the CSV dependency. to higher than 0.3.7. It seems that CSV's api has been drastically altered in any future version.  ([discussion reff](https://github.com/adaltas/node-csv/issues/179))  

### Update Notes:  

**package.json**  
- xlsx 0.8.0 --> 0.12.8  
- csv 0.3.6 --> 0.3.7  
- should 3.1.2 --> 13.2.1  
- mocha 1.17.1 --> 5.0.5   

**travs.yml**  
- node_js: 0.10 --> 8.11.1

**Comment by rodrigograca31** [comment]
So everything is up to date and working fine? Should I accept the commits then?

**Comment by NGrant92** [comment]
tests are passing as well as the travis ci builder. I'd suggest running the tests yourself just to be sure. Otherwise, I'm happy for it to be merged.

**Comment by rodrigograca31** [comment]
Merged.
@NGrant92 thanks for your contributions!

**Pull request merged**
